### ISSUE TITLE
Recalc page fix & XSS

### ISSUE THREAD

**Issue by Tidro** [basavind/kursomir-nota#6]
Исправление ошибки Undefined index: go d2abff29948ae26da22d4cabad38bec3d6493bd9
XSS: d5c72248cd6d7bba4a9ff1ecce830f8f7bd69707 9cb3bcb6bf29bbf5a3cfafb4e09fc1b2ed641410 d948193587c8048326164c10a0c37d9ca1e56cef 32522471c9834d58830dfbec4c7763de1090c793

**Comment by basavind** [comment]
Оформи пожалуйста коммиты пул-реквестами

**Comment by Tidro** [comment]
Не получается)

**Comment by basavind** [comment]
Пичалька (
Ну тогда как будет время - пофиксю

**Comment by basavind** [comment]
Пофиксил
